import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cloudinary Blog Cover Images",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col gap-4 py-6">
          <div className="flex justify-between items-center p-4 w-full max-w-4xl mx-auto">
            <h1 className="text-xl font-black text-center w-full">
              Cloudinary Blog Cover Images
            </h1>
            <div className="flex gap-4 w-full">
              <Link href="/" className="text-sky-400 max-w-2xl mx-auto">
                next image
              </Link>
              <Link
                href="/next-cloudinary"
                className="text-sky-400 max-w-2xl mx-auto"
              >
                next-cloudinary
              </Link>
              <Link
                href="/getCldImage"
                className="text-sky-400 max-w-2xl mx-auto"
              >
                getCldImage
              </Link>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
